# Generated by Django 3.1 on 2020-11-18 11:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import filestorage.misc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.CharField(default=filestorage.misc.generate_token, max_length=8, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32)),
                ('path', models.CharField(max_length=512)),
                ('contributor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.CharField(default=filestorage.misc.generate_uuid, max_length=32, primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=32)),
                ('path', models.CharField(default='', max_length=512)),
                ('size', models.BigIntegerField(default=None, null=True)),
                ('files', models.ManyToManyField(blank=True, to='filestorage.File')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner_folder_set', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='childs', to='filestorage.folder')),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('item', models.FileField(upload_to='uploads/')),
                ('img', models.ImageField(null=True, upload_to='pic/')),
            ],
        ),
        migrations.CreateModel(
            name='Share',
            fields=[
                ('id', models.CharField(default=filestorage.misc.generate_uuid, editable=False, max_length=32, primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('expire', models.DateTimeField(default=None, null=True)),
                ('contributor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributor_share_set', to=settings.AUTH_USER_MODEL)),
                ('files', models.ManyToManyField(related_name='file_share_set', to='filestorage.File')),
                ('folders', models.ManyToManyField(related_name='folder_share_set', to='filestorage.Folder')),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='origin_share_set', to='filestorage.folder')),
            ],
        ),
        migrations.AddField(
            model_name='file',
            name='original',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='filestorage.source'),
        ),
        migrations.AddField(
            model_name='file',
            name='shared',
            field=models.ManyToManyField(related_name='_file_shared_+', to='filestorage.File'),
        ),
        migrations.CreateModel(
            name='DiskQuota',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('limit', models.BigIntegerField()),
                ('used', models.BigIntegerField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=150)),
                ('date', models.DateTimeField(auto_now=True)),
                ('text', models.CharField(max_length=200)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='filestorage.file')),
                ('user', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
